name: Update Age in README

on:
  schedule:
    - cron: '0 23 28 1 *'  # Runs at 23:00 UTC on January 28th (01:00 CET/CEST on January 29th)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug before update
        run: |
          echo "### Before Update ###"
          cat README.md

      - name: Update age in README
        run: |
          # Calculate the new age
          BIRTH_YEAR=2007
          CURRENT_YEAR=$(date +'%Y')
          AGE=$((CURRENT_YEAR - BIRTH_YEAR))

          # Update the README file
          sed -i "s/currently [0-9]\+ years old/currently $AGE years old/" README.md

      - name: Debug after update
        run: |
          echo "### After Update ###"
          cat README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update age in README" || echo "No changes to commit"
          git push
